apiVersion: v1
kind: Service
metadata:
  name: mongo-service 
  namespace: pymongo
spec:
  selector:
    app: mongodb
  type: NodePort
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
      nodePort: 30020
  