apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
  namespace: pymongo
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:              # Mount the volume  ontop of node level; dealing with single node
    path: /mnt/data/db
